language: ruby
services:
  - mongodb
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install cups
  - sudo apt-get install libcupsys2-dev
